name: "Build and Test"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_and_test:
    name: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup CI environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: cd UnicampDiscover && yarn install
      - run: cd UnicampDiscover && npm run test --if-present